# ================= APP =================
server.port=9298

# ================= DB (H2 LOCAL) =================
spring.datasource.url=${DB_URL:jdbc:h2:mem:authdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT =================
jwt.secret=${JWT_SECRET:dev-secret-key}

# ================= FRONTEND =================
frontend.url=http://localhost:5173

# ================= LOGGING =================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG