# ================= DB (MySQL) =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ================= JWT =================
jwt.secret=${JWT_SECRET}

# ================= FRONTEND =================
frontend.url=${FRONTEND_URL}

# ================= LOGGING =================
logging.level.root=INFO